// Package web embeds the compiled React frontend so the Go binary can serve it
// without a separate static-file deployment step.
//
// The dist/ directory is generated by running `npm run build` inside frontend/.
// It must exist before `go build` is invoked. The multi-stage Dockerfile handles
// this automatically.
package web

import "embed"

// FS holds the full contents of the frontend build output.
// The path prefix "dist" is preserved inside the FS, so callers access files as
// "dist/index.html", "dist/assets/…", etc.
//
//go:embed dist
var FS embed.FS
